language: ruby
before_install:
- gem install bundler
rvm:
- 2.2.3
script: bundle exec rake
notifications:
  email:
    recipients:
    - tanayupadhyaya@gmail.com
    on_failure: change
    on_success: never
addons:
  code_climate:
    repo_token: d3c658d7a806da5a99ce2efe84628b8657f463a77d857419dda4c8d71b07dec9
